# Generated by Django 5.0.1 on 2024-01-06 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campany_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='EdinetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edinet_code', models.CharField(max_length=300)),
                ('submitter_type', models.CharField(max_length=300)),
                ('list_class', models.CharField(max_length=300)),
                ('link_or_not', models.BooleanField()),
                ('capital', models.IntegerField()),
                ('close_date', models.DateField()),
                ('submitter_EN', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('industry', models.CharField(max_length=300)),
                ('stock_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DetailElem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elem_id', models.CharField(max_length=300)),
                ('index_name', models.CharField(max_length=300)),
                ('context_id', models.CharField(max_length=300)),
                ('relative_year', models.CharField(max_length=300)),
                ('linkORindivi', models.CharField(choices=[('li', '連結'), ('in', '個別'), ('ot', 'その他')], max_length=100)),
                ('unit_id', models.CharField(max_length=300)),
                ('unit', models.CharField(max_length=300)),
                ('value', models.IntegerField()),
                ('close_date', models.DateField()),
                ('submit_date', models.DateField()),
                ('company_edinet_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyze_company.companydetail')),
            ],
        ),
    ]
