# Generated by Django 5.0.1 on 2024-01-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edinetcode',
            name='link_or_not',
            field=models.BooleanField(null=True),
        ),
    ]
