# Generated by Django 5.0.1 on 2024-01-06 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_company', '0003_alter_edinetcode_capital_alter_edinetcode_close_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edinetcode',
            old_name='submitter_EN',
            new_name='submitter_JA',
        ),
    ]
