# Generated by Django 5.0.1 on 2024-01-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_company', '0004_rename_submitter_en_edinetcode_submitter_ja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edinetcode',
            name='stock_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
