# Generated by Django 5.0.1 on 2024-01-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze_company', '0005_alter_edinetcode_stock_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edinetcode',
            name='capital',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edinetcode',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='edinetcode',
            name='edinet_code',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='edinetcode',
            name='industry',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='edinetcode',
            name='list_class',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='edinetcode',
            name='location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='edinetcode',
            name='submitter_JA',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='edinetcode',
            name='submitter_type',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
